version: 2.1

orbs:
  node: circleci/node@4.1
  win: circleci/windows@2.2.0
  codecov: codecov/codecov@1.0.2

jobs:
  docker-test:
    docker:
      - image: cimg/node:14.16
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn 
      - run:
          name: Run tests
          command: yarn test
      - codecov/upload:
          file: coverage/coverage-final.json
#  windows-test:
#    executor:
#      name: win/default
#      shell: powershell.exe
#    steps:
#      - checkout
#      - run:
#          name: Install packages
#          command: yarn install
#      - run:
#          name: Run Tests
#          command: yarn test

workflows:
  testing: 
    jobs:
      - docker-test
#      - windows-test