{{ if .Values.hpa.enabled }}
{{ if and (eq .Capabilities.KubeVersion.Major "1") (ge .Capabilities.KubeVersion.Minor "8") }}
apiVersion: autoscaling/v2beta1
{{ else }}
apiVersion: autoscaling/v1
{{ end }}
kind: HorizontalPodAutoscaler
metadata:
  name: "{{ .Chart.Name }}-hpa-policy"
  namespace: 
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: "{{ .Chart.Name }}-deployment"
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
{{ end }}