apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: "{{ .Chart.Name }}-root-ingress"
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  tls:
    - hosts:
        - "{{ .Values.ingress }}"
      secretName: "{{ .Chart.Name }}-root-tls-le-key"
  rules:
  - host: "{{ .Values.ingress }}"
    http:
      paths:
      - backend:
          serviceName: "{{ .Chart.Name }}-service"
          servicePort: {{ .Values.service.servicePort }}