# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
revisionHistoryLimit: 1

ingress: tnlfy.live
tunnelifyAdditionalCommand: "--storage redis --redisHost tunnelify-provider-redis-service.tunnelify.svc.cluster.local --redisPort 6379"

image:
  repository: mikesposito/tunnelify-provider
  tag: 0.2.0
  pullPolicy: "Always"
  resources:
    requests:
      cpu: 150m
      memory: 150Mi
    limits:
      cpu: 150m
      memory: 150Mi
  readinessProbe:
    httpGet:
      path: /health
      port: 80
    initialDelaySeconds: 3
    periodSeconds: 5
  livenessProbe:
    httpGet:
      path: /health
      port: 80
    initialDelaySeconds: 40
    periodSeconds: 10
service:
  name: tunnelify-provider
  type: ClusterIP
  servicePort: 80
hpa:
  enabled: false
  minReplicas: 2
  maxReplicas: 6
  metrics:
    cpu:
      targetAverageUtilization: 70
    memory:
      targetAverageUtilization: 70
